carisolusi/urls.py
from django.urls import path
from . import views

app_name='carisolusi'

urlpatterns = [
    path('carisolusi/',views.carisolusi,name='carisolusi'),
    path('hasilsolusi/',views.hasilsolusi,name='hasilsolusi'),
    path('hasilsolusi2/',views.hasilsolusi2,name='hasilsolusi2'),
    path('hasilsolusi3/',views.hasilsolusi3,name='hasilsolusi3'),
]

contact/urls.py
# from .views import profileUtama, musings, schedules, schedulesview, schedulesedit, schedulesdelete
from . import views
from django.urls import path

app_name= 'contact'

urlpatterns = [
	# path('', views.profileUtama, name='home'),
	path('contact/', views.contact, name='contact' ),
	# path('schedules-add/', views.schedules_add, name='schedules_add'),
	# path('schedulesView/', views.schedulesview, name ="schedulesview"),
 #    path('schedules/delete/<int:id>', views.schedulesdelete, name='schedulesdelete'),
]

homeReview/urls.py
from django.urls import path
from . import views

app_name = 'homeReview'

urlpatterns = [
    path('',views.homeReview,name='homeReview'),
]

inippw/urls.py
from django.contrib import admin
from django.urls import path, include
from jadwaldok.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tugas.urls')),
    path('',include('jadwaldok.urls',namespace='jadwaldok')),
    path('',include('contact.urls', namespace='contact')),
    path('',include('homeReview.urls', namespace = 'homeReview')),
    path('',include('carisolusi.urls', namespace = 'carisolusi'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

jadwaldok/urls.py
from django.urls import path
from . import views

app_name='jadwaldok'

urlpatterns = [
    path('jadwal/',views.jadwal,name='jadwal'),
]

tugas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('inibukanapaapa/',views.home,name='index'),
]

carisolusi/models.py
from django.db import models


penyakit1 = (
    (1,"Sakit kepala"),
    (2,"Muntah-Muntah"),
    (3,"Kulit pucat")
)
penyakit2 = (
    (4,"Suhu badan tinggi"),
    (5,"Warna urine berubah"),
    (6,"Sesak napas")
)
penyakit3 = (
    (7,"Sesak napas"),
    (8,"Nyeri punggung"),
    (9,"Batuk-batuk")
)
# Create your models here.
class Penyakit(models.Model):

    Keluhan1 = models.IntegerField(choices = penyakit1)
    Keluhan2 = models.IntegerField(choices = penyakit2)
    Keluhan3 = models.IntegerField(choices = penyakit3)
    def __str__(self):
        return self.Keluhan1

contact/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class Contact(models.Model):
      cat 		=  (
			        ('Keluhan', 'Keluhan'),
			        ('Pembayaran', 'Pembayaran'),
			        ('Lainnya', 'Lainnya'),
				    )
      kategori = models.CharField(max_length=50, choices=cat, default='Keluhan')
      judul = models.CharField(max_length=250)
      isi = models.TextField()
      email = models.CharField(max_length=250)
      updated = models.DateTimeField()  
      def __str__(self):
          return self.judul

homeReview/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Review(models.Model):
    tanggapan = models.TextField(u'Bagaimana tanggapanmu?')
    saran = models.TextField(u'Apakah ada fitur yang perlu diubah?')

    # def publish(self):
    #     self.published_date = timezone.now()
    #     self.save()

    # def __str__(self):
    #     return self.title

jadwaldok/models.py
from django.db import models


class jadwalAppointment(models.Model):
	DOKTER= (
		("1","Meldi"),
		('2',"Safa"),
		('3',"Nuel"),
		('4',"Bella"),
		)
	nama = models.CharField(max_length= 50)
	tanggal = models.DateField()
	waktu = models.TimeField(auto_now=True)
	keluhan =models.TextField()
	dokter = models.CharField(max_length = 100,choices=DOKTER)
	status = models.CharField(max_length=50, default="Pending")

	def __str__(self):
		return "{}. {}".format(self.id,self.nama)
		
# Create your models here.

tugas/models.py
from django.db import models

# Create your models here.

carisolusi/forms.py
from django import forms
from .models import Penyakit

class HasilPenyakit(forms.ModelForm):
    class Meta:
        model = Penyakit
        fields = ['Keluhan1', 'Keluhan2', 'Keluhan3']

contact/forms.py
from django import forms
from .models import Contact
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact       
        fields = ['kategori','judul','isi','email']

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save person'))
        # self.fields['email'].required = True






        

homeReview/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = '__all__'

jadwaldok/forms.py
from django import forms
from . import models

class formAppointment(forms.Form):
	nama = forms.CharField(required=True)
	tanggal = forms.DateField(
		widget=forms.SelectDateWidget)
	waktu = forms.TimeField()
	keluhan = forms.CharField()
	dokter = forms.ChoiceField(choices=models.jadwalAppointment.DOKTER)
		

tugas/forms.py
from django import forms

##Create your forms here

carisolusi/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import HasilPenyakit
from . import forms

# Create your views here.
def carisolusi(request):
    if request.method == 'POST':
        form = HasilPenyakit(request.POST)
        if form.is_valid():
            kel1 = request.POST.get('Keluhan1')
            kel2 = request.POST.get('Keluhan2')
            kel3 = request.POST.get('Keluhan3')
            if int(kel1) == 1:
                return redirect('/hasilsolusi/')
            elif int(kel1) == 2:
                return redirect('/hasilsolusi2/')
            else:
                return redirect('/hasilsolusi3/')
    else:
        form = HasilPenyakit()
    return render(request, 'carisolusi.html', {'form': form})

def hasilsolusi(request):
    return render(request, 'hasilsolusi.html')
def hasilsolusi2(request):
    return render(request, 'hasilsolusi2.html')
def hasilsolusi3(request):
    return render(request, 'hasilsolusi3.html')

    #blabla

contact/views.py
from django.shortcuts import render, redirect


from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from .forms import ContactForm
from .models import Contact
import pprint
import datetime
import time

# def contact(request):
# 	return render(request, 'contact.html')	

def contact(request):
    # pprint.pprint(request.POST)
    if request.method == 'POST':
       form = ContactForm(request.POST)
       if form.is_valid():
          contact = form.save(commit=False)
          contact.updated = datetime.datetime.now()
          contact.save()
          return HttpResponseRedirect('')
    else:
       form = ContactForm()
    return render(request, 'contact.html', {'form': form})

homeReview/views.py
from django.shortcuts import render
from .forms import ReviewForm
from django.contrib import messages

# Create your views here.
def homeReview(request):
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            form.save()
            form = ReviewForm()
            messages.success(request, 'Review sebelumnya sudah berhasil terkirim!') 
    else:
        form = ReviewForm()
    return render(request,'homeReview.html',{'form':form})

jadwaldok/views.py
from django.shortcuts import render, redirect
from . import models, forms
from .forms import formAppointment
from .models import jadwalAppointment

# Create your views here.
def jadwal(request):
	createAppointment = formAppointment(request.POST or None)
	dataAppoint= jadwalAppointment.objects.all()
	context = {
		"appointments":dataAppoint,
		"create_jadwal":createAppointment,
	}
	if request.method=="POST":
		if createAppointment.is_valid():
			jadwalAppointment.objects.create(
				nama = createAppointment.cleaned_data.get('nama'),
				tanggal = createAppointment.cleaned_data.get('tanggal'),
				waktu =createAppointment.cleaned_data.get('waktu'),
				keluhan = createAppointment.cleaned_data.get('keluhan'),
				dokter = createAppointment.cleaned_data.get('dokter'),
				)
	return render(request,"pages/jadwal.html",context)

	# if request.method = "POST":
	# 	if createAppointment.is_valid():
	# 		

tugas/views.py
from django.shortcuts import render,redirect

# Create your views here.
def home(request):
    return render(request,'pages/index.html',{})

carisolusi/templates/carisolusi.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'carisolusi.css' %}">
    <!-- Bootstrap CSS -->
    <title>Cari Solusi</title>
    {% include "headBase.html" %}
  </head>
  <body class = "carisolusibody">
      {% include "navBase.html" %}
      <h1 class = "judulcarisolusi"><center>Cari Solusi</center></h1>
      <form class="css" method="POST">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-sm-1"></div>
            <div class="form-group col-sm-10 tag">
                {% for fields in form %}
                    {{ fields.label_tag }}
                    <br>
                    {{ fields }}
                    <br>
                {% endfor %}
            </div>
        </div>
        <div class="form-row">
            <div class="col-sm-1"></div>
            <input type="submit" class="btn btn-primary float-right" value="Submit">
        </div>
    </form>                

                        
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

carisolusi/templates/hasilsolusi.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'carisolusi.css' %}">
    <!-- Bootstrap CSS -->
    <title>Hasil Solusi</title>
    {% include "headBase.html" %}
    <style>
    h1{
      margin-top: 100px;
    }
    </style>
  </head>
  <body class = "bodyhasilsolusi">
    {% include "navBase.html" %}
    <h1><center>Kamu Flu!</center></h1>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

carisolusi/templates/hasilsolusi2.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'carisolusi.css' %}">
    <!-- Bootstrap CSS -->
    <title>Hasil Solusi</title>
    {% include "headBase.html" %}
    <style>
        h1{
          margin-top: 100px;
        }
    </style>
  </head>
  <body class = "bodyhasilsolusi2">
    {% include "navBase.html" %}
    <h1 class = "hasilsolusicss2"><center>Kamu Demam Berdarah!</center></h1>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

carisolusi/templates/hasilsolusi3.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'carisolusi.css' %}">
    <!-- Bootstrap CSS -->
    <title>Hasil Solusi</title>
    {% include "headBase.html" %}
    <style>
        h1{
          margin-top: 100px;
        }
    </style>
  </head>
  <body class = "bodyhasilsolusi3">
    {% include "navBase.html" %}
    <h1 class = "hasilsolusicss3"><center>Kamu Tipes!</center></h1>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

carisolusi/templates/headBase.html
{% load static %}
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
 <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
 <!-- <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+SansOpen+Sans:800&display=swap"> -->
 <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet"> -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600&display=swap" rel="stylesheet">

carisolusi/templates/navBase.html
<nav class="navbar fixed-top navbar-light navbar-bg">
  <a class="nav-link active text bold brand" href="/">
    Temu.kan
  </a>
<ul class="nav justify-content-end">
  <li class="nav-item">
    <a class="nav-link active text" href="{% url 'jadwaldok:jadwal' %}">Apppointment</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text" href="{% url 'contact:contact' %}">Contact Us</a>
  </li>
</ul>
</nav>

contact/templates/contact.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>Temu.kan</title>
		{% include "headBase.html" %}
	</head>

	<body>
		{% include "navBase.html" %}
		<div id="contact">		
		<h2>Contact Us</h2>	

		{% load crispy_forms_tags %}

		<div class="contact">
			<div class="col-md-9 p-0 mx-auto">			
			  	<form action="/contact/" method="post" name="form" novalidate>
					{% csrf_token %}
				    <div class="form-group row col-md-11 mt-4 mx-auto">
				      <label for="inputPassword" class=" col-sm-2 my-auto label-input">Kategori</label>
				      <div class="col-sm-10">
				      	{{ form.kategori }}		
				  	  </div>
				  	  
				    </div>

				    <div class="form-group row col-md-11 mt-5 mx-auto">
				      <label for="inputPassword" class=" col-sm-2 my-auto label-input">Judul Pesan</label>
				      <div class="col-sm-10">
				      	{{ form.judul }}		
				      </div>
				    </div>
				  
				    <div class="form-group row col-md-11 mt-5 mx-auto">
				      <label for="inputMessage" class="control-label requiredField col-sm-2 my-2 label-input"> Isi Pesan</label>
				      <div class="col-sm-10">
				      	{{ form.isi }}		
				  	  </div>
				    </div>

				    <div class="form-group row col-md-11 mt-5 mx-auto">
				      <label for="inputPassword" class="control-label requiredField col-sm-2 my-auto label-input">Email</label>
				      <div class="col-sm-10">
				      	{{ form.email }}		
				      </div>
				    </div>
				 
				   <div class="form-row">
				    <div class="form-group col-md-4 mt-4 mx-auto text-center">
				      <input type="submit" class="btn btn-md btn-primary submits" value="Submit" name="submit">
				    </div>
				  </div>

				  <!-- <div class="alert alert-light">
    				<strong>Light!</strong> You should <a href="#" class="alert-link">read this message</a>.
  				</div> -->

				</form>
			</div>
		</div>
	</body>
</html>

contact/templates/headBase.html
{% load static %}
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
 <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
 <!-- <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+SansOpen+Sans:800&display=swap"> -->
 <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet"> -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600&display=swap" rel="stylesheet">

contact/templates/navBase.html
<nav class="navbar fixed-top navbar-light navbar-bg">
  <a class="nav-link active text bold brand" href="/">
    Temu.kan
  </a>
<ul class="nav justify-content-end">
  <li class="nav-item">
    <a class="nav-link active text" href="{% url 'jadwaldok:jadwal' %}">Apppointment</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text" href="{% url 'contact:contact' %}">Contact Us</a>
  </li>
</ul>
</nav>

homeReview/templates/homeReview.html
{% load static %}
<!doctype html>
<head>{% include 'headBase.html' %}
    <title>Temu.kan</title>

</head>
<body class="body-bg padding-main text">
{% include 'navBase.html' %}
<div class="padding-welcome">
<div class="row text-center">
    <div class="col-12 p0">
        <h1 class="display-4">Coba <b>Temu.kan</b> solusi masalah<br>kesehatanmu disini</h1>
        <button type="button" onClick="window.location.href='{% url 'carisolusi:carisolusi' %}'" class="btn btn-outline-light btn-curve margin-top-1"><b>Cari Solusi</b></button>
        <h6 class="margin-top-5"><b>Sudah pernah menemukan solusi?</b></h6>
        <button type="button" onClick="document.getElementById('review').scrollIntoView();" class="btn btn-outline-light btn-curve margin-top-1"><b>Buat Review</b></button>
    </div>
</div>
</div>
<div class="padding-review" id="review">
<div class="row text-center">
    <div class="col-12 p0">
        <h1 class="text-orange margin-bottom-5"><b>Review</b></h1>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <div  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </div>
            {% endfor %}
        </ul>
    {% endif %}
        <form method="POST">
            {% csrf_token %}
            <table class="form">
            {{ form.as_table }}
            <tr><td colspan="2">
                    <button type="submit" class="btn btn-primary btn-curve margin-top-1"><b>Submit</b></button>
            </td></tr>
            </table> 
        </form>
    </div>
</div>
</div>
</body>

homeReview/templates/navBase.html
<nav class="navbar fixed-top navbar-light navbar-bg">
  <a class="nav-link active text bold brand" href="/">
    Temu.kan
  </a>
<ul class="nav justify-content-end">
  <li class="nav-item">
    <a class="nav-link active text" href="{% url 'jadwaldok:jadwal' %}">Apppointment</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text" href="{% url 'contact:contact' %}">Contact Us</a>
  </li>
</ul>
</nav>

jadwaldok/templates/navBase.html
<nav class="navbar fixed-top navbar-light navbar-bg">
  <a class="nav-link active text bold brand" href="/">
    Temu.kan
  </a>
<ul class="nav justify-content-end">
  <li class="nav-item">
    <a class="nav-link active text" href="{% url 'jadwaldok:jadwal' %}">Apppointment</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text" href="{% url 'contact:contact' %}">Contact Us</a>
  </li>
</ul>
</nav>

tugas/templates/navBase.html
<nav class="navbar fixed-top navbar-light navbar-bg">
  <a class="nav-link active text bold brand" href="/">
    Temu.kan
  </a>
<ul class="nav justify-content-end">
  <li class="nav-item">
    <a class="nav-link active text" href="{% url 'jadwaldok:jadwal' %}">Apppointment</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text" href="{% url 'contact:contact' %}">Contact Us</a>
  </li>
</ul>
</nav>

tugas/templates/pages/index.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Jadwal Appointment</title>
	{% include "headBase.html" %}
</head>
<body>
	{% include "navBase.html" %}
</body>
</html>